version: '3.8'

services:
  aiweb:
    container_name: aiweb
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - .:/app
    tty: true
    stdin_open: true

    